sequences:
  - protein:
      id: A
      sequence: DTLCIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGKCNIAGWILGNPECESLSTASSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSNKGVTAACPHAGAKSFYKNLIWLVKKGNSYPKLNQSYINDKGKEVLVLWGIHHPSTTADQQSLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQEGRMNYYWTLVEPGDKITFEATGNLVVPRYAFTMERNAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNIHPITIGKCPKYVKSTKLRLATGLRNVPS
      msa: empty
  - protein:
      id: B
      sequence: IEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKI
      msa: empty
  - protein:
      id: H
      sequence: MPSPPGNLRVTDVTSTSVTLSWEPPPGPITGYRVEYREAGGEWKEVTVPGSETSYTVTGLKPGTEYEFRVRAVNGAGEGPGGGGPSSVSVTTEIDKPSQ
      msa: empty

templates:
  - cif: /work/lpdi/users/xkong/codes/boltz_bindcraft/demo/templates/6xgc.cif
    chain_id: [A, B]
    template_id: [A, B]

generator:
  config:
    lr: 1.0
    max_inner_steps: 10
    max_outer_steps: 100
    # inner_enc_recycling_steps: 0
    # inner_diffusion_steps: 20
    sample_k: 5
  loss:
    - class: pLDDT
      weight: 0.5
    - class: CPipTM
      chain_pairs: [[A, H], [B, H]]
      weight: 0.0
    - class: FWAway
      binder_chains: [H]
      contact_th: 10.0
      weight: 1.0
    - class: Epitope
      epitope: [[B, 11], [B, 32], [B, 35]]
      weight: 1.0
  masks:
    H: "000000000000000000000011111111100000000000000000111111000000000000000000001111111111000000000000000"